# Generated by Django 2.0.5 on 2018-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=200)),
            ],
        ),
    ]
