# Generated by Django 2.0.5 on 2018-07-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
