# Generated by Django 2.0.5 on 2018-07-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_auto_20180706_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
